giris/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import LoginView, RegisterView,logout_view

app_name = 'giris'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', logout_view, name='logout')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

insaatsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import IndexView, DashView
from musteri.views import AjaxMusteriList
from rest_framework.routers import DefaultRouter

# router = DefaultRouter()
# router.register(r'musteri', MusteriViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
   
    path('', IndexView.as_view(), name='index'),
    path('account/', include('giris.urls', namespace='giris')),
    path('<userfirm>/', DashView.as_view(), name='dash'),
    path('<userfirm>/musteri/', include('musteri.urls', namespace='musteri')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/accounts/login.html
<h1>Login</h1>

<form action="{% url 'giris:login' %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" id="submit">Login</button>
</form>

templates/accounts/register.html
<h1>Register</h1>

<form action="{% url 'giris:register' %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" id="submit">Register</button>
</form>