giris/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import LoginView, RegisterView,logout_view

app_name = 'giris'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', logout_view, name='logout')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

insaatsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import IndexView, DashView
from musteri.views import AjaxMusteriList
from rest_framework.routers import DefaultRouter

# router = DefaultRouter()
# router.register(r'musteri', MusteriViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
   
    path('', IndexView.as_view(), name='index'),
    path('account/', include('giris.urls', namespace='giris')),
    path('<userfirm>/', DashView.as_view(), name='dash'),
    path('<userfirm>/musteri/', include('musteri.urls', namespace='musteri')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

musteri/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import Yenimusteri,Musteridetay, Musteriupdate, AjaxMusteriList, musteriweb_list
from rest_framework.routers import DefaultRouter


app_name = 'musteri'



urlpatterns = [
    path('yeni/', Yenimusteri.as_view(), name='yenimusteri'),
    path('ajax/musteri/', AjaxMusteriList.as_view(), name='ajaxmusteri'),
    path('liste/', musteriweb_list, name='musterilistesi'),
    path('<int:pk>/', Musteridetay.as_view(), name='musteridetay'),
    path('<int:pk>/edit', Musteriupdate.as_view(), name='musteriupdate'),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

musteri/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django.db.models import CharField, EmailField, DateTimeField, ForeignKey, OneToOneField




# Create your models here.

CINSIYET_CHOICES=[
        ('K', 'Kadın'),
        ('E', 'Erkek'),
        ('D', 'Diğer'),]

EGITIM_CHOICES=[
        ('I', 'İlkokul'),
        ('O', 'Ortaokul'),
        ('L', 'Lise'),
        ('M', 'Önlisans'),
        ('U', 'Lisans'),
    ]

class Musteri(models.Model):

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ad = models.CharField(max_length=50, blank=True, null=True)
    telefon = models.CharField(max_length=11, blank=True, null=True) 
    email= models.EmailField(max_length=254, blank=True, null=True)
    dog_tar= models.DateField(blank=True, null=True)
    created=models.DateTimeField(auto_now_add=True,blank=True, null=True )
    updated=models.DateTimeField(auto_now=True,blank=True, null=True)
    
    cinsiyet=models.CharField(max_length=1, choices=CINSIYET_CHOICES,blank=True, null=True ) 
    
    egitim=(CharField(max_length=1, choices=EGITIM_CHOICES,blank=True, null=True ) )
    adres=models.TextField(max_length=254,blank=True, null=True)

    def __str__(self):
        return self.ad
   
    def get_absolute_url(self):
         return reverse("musteri:yenimusteri", kwargs={'slug': self.user.userfirm.slug})    
   
            

musteri/forms.py
from django import forms

from .models import Musteri
from django.db.models import CharField, EmailField, DateTimeField, ForeignKey, OneToOneField
from bootstrap_datepicker_plus import DatePickerInput




class Musteriform(forms.ModelForm):
    class Meta:
        model=Musteri
        fields = ['ad', 'telefon', 'email', 'dog_tar', 'cinsiyet', 'egitim', 'adres']
    
        widgets = {
            'dog_tar': DatePickerInput(options={
                    "format": "MM/DD/YYYY", # moment date-time format
                    "showClose": True,
                    "showClear": True,
                    "showTodayButton": True,
                }),
        }
    

musteri/views.py
from django.shortcuts import render, get_object_or_404
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import ListView, DetailView, View
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from rest_framework import viewsets
from .serializers import MusteriSerializer
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.core.serializers.json import DjangoJSONEncoder
from django.contrib.auth import get_user_model

from django.db.models.functions import Lower
from .forms import Musteriform
from django.contrib import messages
from django.urls import reverse
from .models import Musteri
import json
import re
# Create your views here.
User = get_user_model()

class Yenimusteri(View):
    #template_name="musteri/yenimusteri"
    def get(self, *args, **kwargs):
        userfirm=self.request.user.userfirm.slug
        
        form = Musteriform()
        context = {
                'form': form,
                'userfirm':userfirm,
                
             
                
            }
        return render (self.request, "musteri/yenimusteri.html", context)
    def post(self, *args, **kwargs):
           
        userfirm=self.request.user.userfirm.slug
       
        form = Musteriform(self.request.POST or None)
        context = {
                             
                'form': form,
                'userfirm':userfirm,
              
           
              
             
            }       
        
        

        if form.is_valid():
            musteri=Musteri() 
                       
            musteri.ad = form.cleaned_data.get('ad')
            musteri.telefon = form.cleaned_data.get('telefon')
            musteri.user=self.request.user     
            musteri.save() 
            pk=musteri.pk 
            messages.success(self.request, "Yeni Müşteri Kaydedildi")
            return redirect('musteri:musteridetay', userfirm, pk)
        else:
           messages.warning(self.request, 'Form is not valid')
           return redirect('musteri:yenimusteri', context)


class Musteridetay(View):
    #template_name="musteri/yenimusteri"
    def get(self, *args, **kwargs):
        userfirm=self.request.user.userfirm.slug
        
        musteri=Musteri.objects.get(pk=self.kwargs.get('pk'))
    
        context = {
                'musteri': musteri,
                'userfirm':userfirm,
             'pk':musteri.pk,
                
            }
        return render (self.request, "musteri/musteridetay.html", context)        

    

class AjaxMusteriList(View):
    serializer_class = MusteriSerializer
        
    def post(self, request, userfirm):
        musteris = self._datatables(request, userfirm)
        userfirm=self.request.user.userfirm.slug 
        print(musteris,)
        return HttpResponse(json.dumps(musteris, cls=DjangoJSONEncoder), content_type='application/json')
        
    def _datatables(self, request, userfirm):
        
        datatables = request.POST
        userfirm=self.request.user.userfirm.slug 
        # Ambil draw
        draw = int(datatables.get('draw'))
        # Ambil start
        start = int(datatables.get('start'))
        # Ambil length (limit)
        length = int(datatables.get('length'))
        # Ambil data search
        search = datatables.get('search[value]')
        order_idx = int(datatables.get('order[0][column]'))
        order_dir = datatables.get('order[0][dir]')
        order_col = 'columns[' + str(order_idx) + '][data]'
        order_col_name = datatables.get(order_col)
        # Set record total
        if not self.request.user.is_superuser:
            records_total = Musteri.objects.filter(user__userfirm=self.request.user.userfirm).exclude().count()
        else:
            records_total = Musteri.objects.all().count()
        # Set records filtered
        records_filtered = records_total
        # Ambil semua invoice yang valid
        if not self.request.user.is_superuser:
            musteris = Musteri.objects.filter(user__userfirm=self.request.user.userfirm)
        else:
            musteris = Musteri.objects.all()
            
        if search:
            musteri2=Musteri.objects.filter(user__userfirm=self.request.user.userfirm)
            musteris = musteri2.filter(
                    Q(ad__icontains=search)|
                    Q(telefon__icontains=search)|
                    Q(email__icontains=search)).exclude().order_by(Lower('ad'))
            records_total = musteris.count()
            records_filtered = records_total

        # Atur paginator
        
    
    
       

        if (order_dir == "desc"):
            order_col_name =  str('-' + order_col_name)
            
            
            idx=0
            for itemcol in datatables:
                colname = 'columns['+str(idx)+'][data]'
                                            
                colname = datatables.get(colname)
                                           
                idx+=1
                
                musteris = musteris.order_by(order_col_name, 'pk')
        
        else:
                          
                musteris = musteris.order_by(order_col_name, 'pk')        

   
        paginator = Paginator(musteris, length)

        page_number = start / length + 1

        try:
            object_list = paginator.page(page_number).object_list
        except PageNotAnInteger:
            object_list = paginator.page(1).object_list
        except EmptyPage:
            object_list = paginator.page(1).object_list

        userfirm=request.user.userfirm.slug
        data = [
            {
            
                'id':inv.id,
                'ad': inv.ad,
                'telefon': inv.telefon,
                'email': inv.email,
                'dog_tar': inv.dog_tar,
                'cinsiyet': inv.cinsiyet,
                'egitim': inv.egitim,
                'adres': inv.adres,
                'created': inv.created,
                'updated':inv.updated,
                'userfirm':userfirm
                
            } for inv in object_list
            ]
        
        return {
            'draw': draw,
            'recordsTotal': records_total,
            'recordsFiltered': records_filtered,
            'data': data,
            'userfirm': userfirm,
        }
   
def musteriweb_list(request, userfirm):
    userfirm=request.user.userfirm.slug
  
    
    data_context = { 'userfirm':userfirm,}
    return render(request, 'musteri/musterilist.html', data_context )


class Musteriupdate(View):
    #template_name="musteri/musteriupdate"
    def get(self, *args, **kwargs):
        userfirm=self.request.user.userfirm.slug

        musteri=Musteri.objects.get(pk=self.kwargs.get('pk'))
        
        
        form = Musteriform(instance=musteri)
        context = {
                'form': form,
                'userfirm':userfirm,
                'musteri': musteri,
                'pk':musteri.pk 
              
                            }
        
       
        
        
        return render (self.request, "musteri/musteriupdate.html", context)
    def post(self, *args, **kwargs):
        musteri=Musteri.objects.get(pk=self.kwargs.get('pk'))      
        userfirm=self.request.user.userfirm.slug
        pk=musteri.pk 
        form = Musteriform(self.request.POST or None, instance=musteri)
        context = {
                             
                'form': form,
                'userfirm':userfirm,
                'musteri': musteri,
                'pk':musteri.pk 
              
             
            }       
        
        

        if form.is_valid():
            musteri=Musteri.objects.get(pk=self.kwargs.get('pk'))
            musteri.ad = form.cleaned_data.get('ad')
            musteri.telefon = form.cleaned_data.get('telefon')
            musteri.email = form.cleaned_data.get('email')
            musteri.dog_tar = form.cleaned_data.get('dog_tar')
            musteri.user=self.request.user     
            musteri.save() 
           
            messages.success(self.request, "Müşteri bilgileri Güncellendi")
            return redirect('musteri:musteridetay', userfirm, pk)
        else:
           messages.warning(self.request, 'Form is not valid')
           return redirect('musteri:musteriupdate', userfirm, pk)

templates/musteri/musteridetay.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="col-md-6">
   
 <table  class="table table-bordered" style="width:100%">
	<thead>
		<tr>
            
			<td >Ad Soyad</td>
            <td >{{ musteri.ad|default_if_none:"" }}</td>
        </tr>
        <tr>
            <td>Telefon</td>
            <td >{{musteri.telefon|default_if_none:""}}</td>
        </tr>
        <tr>
           
            <td >Email</td>
            <td >{{musteri.email|default_if_none:""}}</td>
        </tr>
        <tr>
			<td >Doğum Tarihi</td>
            <td >{{musteri.dog_tar|default_if_none:""}}</td>
        </tr>
        <tr>
            <td >Cinsiyet</td>
            <td >{{musteri.cinsiyet|default_if_none:""}}</td>
        </tr>
        <tr>
            <td >Eğitim</td>
            <td >{{musteri.egitim|default_if_none:""}}</td>
        </tr>
        <tr>
            <td >Adres</td>
            <td >{{musteri.adres|default_if_none:""}}</td>
        </tr>
        <tr>
            <td >Kayıt Zamanı</td>
            <td >{{musteri.created|default_if_none:""}}</td>
            
        </tr>
        <tr>

            <td >Güncelleme Zamanı</td>
            <td >{{musteri.updated}}</td>
        </tr>
    </table> 
    <div class="col-md-6">

        <!-- <a type="submit" href="{{userfirm}}/musteri/{{pk}}/edit" class="btn btn-primary">Güncelle</a> -->
       
        <a type="submit" href="{% url 'musteri:musteriupdate' userfirm pk %}" class="btn btn-primary">Güncelle</a>
       
        <button type="button" class="btn btn-danger">Sil</button>
    </div>
</div>

{% endblock %}     




	</thead>

templates/musteri/musterilist.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="col-md-6">

 <table id="musteri" class="display" style="width:100%">
	<thead>
		<tr>
			<th >Ad Soyad</th>
			
			<th>Telefon</th>
			<th >Email</th>
			<th >Doğum Tarihi</th>
			<th >Cinsiyet</th>
			<th >Eğitim</th>
			<th >Adres</th>
			<th >Kayıt Zamanı</th>
			<th >Güncelleme Zamanı</th>
			
		</tr>
	</thead>

	<tfoot>
		<tr>
			<th >ad</th>
			
			<th>Telefon</th>
			<th >Email</th>
			<th >Doğum Tarihi</th>
			<th >Cinsiyet</th>
			<th >Eğitim</th>
			<th >Adres</th>
			<th >Kayıt Zamanı</th>
			<th >Güncelleme Zamanı</th>
	
			
		</tr>
	</tfoot>
</table> 
	</div>

  {% endblock %}
  {% block extra_js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
<script src="https:////cdn.datatables.net/plug-ins/1.10.21/sorting/turkish-string.js"></script>
<script>

 $(document).ready(function() {
	
  var otable=  $('#musteri').DataTable( {
            "processing": true,
            "serverSide": true,
			"ajax": {
                "url": "{% url 'musteri:ajaxmusteri' userfirm %}",
                "type": "POST",
                "data": {"csrfmiddlewaretoken": "{{ csrf_token }}"
        	}
                
            },
			"language":{
			"sDecimal":        ",",
			"sEmptyTable":     "Tabloda herhangi bir veri mevcut değil",
			"sInfo":           "_TOTAL_ kayıttan _START_ - _END_ arasındaki kayıtlar gösteriliyor",
			"sInfoEmpty":      "Kayıt yok",
			"sInfoFiltered":   "(_MAX_ kayıt içerisinden bulunan)",
			"sInfoPostFix":    "",
			"sInfoThousands":  ".",
			"sLengthMenu":     "Sayfada _MENU_ kayıt göster",
			"sLoadingRecords": "Yükleniyor...",
			"sProcessing":     "İşleniyor...",
			"sSearch":         "Ara:",
			"sZeroRecords":    "Eşleşen kayıt bulunamadı",
			"oPaginate": {
				"sFirst":    "İlk",
				"sLast":     "Son",
				"sNext":     "Sonraki",
				"sPrevious": "Önceki"
			},
			"oAria": {
				"sSortAscending":  ": artan sütun sıralamasını aktifleştir",
				"sSortDescending": ": azalan sütun sıralamasını aktifleştir"
			},
			"select": {
				"rows": {
					"_": "%d kayıt seçildi",
					"0": "",
					"1": "1 kayıt seçildi"
				}},},
			

            "columns": [
				
                { "data": "ad" },
                { "data": "telefon" },
               
                { "data": "email" },
                { "data": 'dog_tar',
			"type": 'date',
			"render": function (data, type, row) { return data ? moment(data).format('DD/MM/YYYY') : ''; }
				
				},
				{ "data": "cinsiyet" },
                { "data": "egitim" },
                { "data": "adres" },
                { "data": "created" },
                { "data": "updated" },
			
		
            ], 
			"columnDefs": [
         { type: 'turkish', targets: '_all' }
     ]
		
        } );
	
		$("#musteri").on('click', 'tbody tr', function() {
			
			
			var rowdata= otable.row( this ).data() ;
			var idd=rowdata.userfirm+'/musteri/'+rowdata.id; 
			window.location.pathname=idd;
		} );
    } );

</script>
{% endblock extra_js %}

templates/musteri/musteriupdate.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<body class="bg-gradient-primary"></body>

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              
              <div class="col-lg-8">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Müşteri Güncelleme Ekramı</h1>
                  </div>
                  <form action="{% url 'musteri:musteriupdate' userfirm pk %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                      <input type="text" class="form-control" id="ad" name="ad" maxlength="50" value={{musteri.ad}} required>
                    </div>
                    <div class="form-group">
                      <input type="text" class="form-control" id="telefon" name="telefon" maxlength="11" value={{musteri.telefon}} required>
                    </div>

                    <div class="form-group">
                      <input type="text" class="form-control" id="email" name="email" value={{musteri.email| default_if_none:"" }}>
                    </div>
                    <div class="form-group row">
                      <label class="col-2 col-form-label">Doğum Tarihi</label>
                      <div class="col-10">
                        <input class="form-control" type="date" value="{{musteri.dog_tar}}" id="dog_tar" name="dog_tar">
                      </div>
                    </div>
                    <!-- <div class="form-group">
                      <div class="custom-control custom-checkbox small">
                        <input type="checkbox" class="custom-control-input" id="customCheck">
                        <label class="custom-control-label" for="customCheck">Remember Me</label>
                      </div>
                    </div> -->
                    <button class="btn btn-primary btn-block" type="submit" id="submit">
                     Müşteriyi Güncelle
                    </button>
                    <hr>
                    <!-- <a href="index.html" class="btn btn-google btn-user btn-block">
                      <i class="fab fa-google fa-fw"></i> Login with Google
                    </a>
                    <a href="index.html" class="btn btn-facebook btn-user btn-block">
                      <i class="fab fa-facebook-f fa-fw"></i> Login with Facebook
                    </a> -->
                  </form>
                  <!-- <hr>
                  <div class="text-center">
                    <button class="small" href="forgot-password.html">Forgot Password?</button>
                  </div> -->
                  <!-- <div class="text-center">
                    <a class="small" href="register.html">Create an Account!</a>
                  </div> -->
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  

</body>

{% endblock %}

templates/musteri/yenimusteri.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<body class="bg-gradient-primary"></body>

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              
              <div class="col-lg-8">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Yeni Müşteri</h1>
                  </div>
                  <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                      <input type="text" class="form-control" id="ad" name="ad" placeholder="Ad Soyad..." maxlength="50" required>
                    </div>
                    <div class="form-group">
                      <input type="text" class="form-control" id="telefon" name="telefon" placeholder="Telefon Numarası" maxlength="11" required>
                    </div>
                    <!-- <div class="form-group">
                      <div class="custom-control custom-checkbox small">
                        <input type="checkbox" class="custom-control-input" id="customCheck">
                        <label class="custom-control-label" for="customCheck">Remember Me</label>
                      </div>
                    </div> -->
                    <button class="btn btn-primary btn-block" type="submit" id="submit">
                     Yeni Müşteri Kaydet
                    </button>
                    <hr>
                    <!-- <a href="index.html" class="btn btn-google btn-user btn-block">
                      <i class="fab fa-google fa-fw"></i> Login with Google
                    </a>
                    <a href="index.html" class="btn btn-facebook btn-user btn-block">
                      <i class="fab fa-facebook-f fa-fw"></i> Login with Facebook
                    </a> -->
                  </form>
                  <!-- <hr>
                  <div class="text-center">
                    <button class="small" href="forgot-password.html">Forgot Password?</button>
                  </div> -->
                  <!-- <div class="text-center">
                    <a class="small" href="register.html">Create an Account!</a>
                  </div> -->
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  

</body>

{% endblock %}